# 异常处理机制

- 抛出异常
- 捕获异常
- 异常处理五个关键字
  - try,catch,finally,throw,throws

```java
package exception;

import oop.demo10.Test;

public class Exception02 {
    public static void main(String[] args) {

        int a = 1;
        int b = 0;

        try {
            new Exception02().test(1,0);
        }catch (ArithmeticException e){
            e.printStackTrace();
        }

        try { //监控区域
            System.out.println(a/b);
        }catch (Throwable e){ //catch(想要捕获的异常类型)捕获异常,可以写多个catch,但只执行一个 从上到下 从小到大
            e.printStackTrace();//打印错误的栈信息
            System.out.println("程序出现异常变量B不能为0");
        }finally { //处理善后工作,不管出不出异常这里都会被执行
            System.out.println("finally");
        }

        //finally 可以不要,运用在 IO流中 关闭不必要的资源

    }

    public void a(){
        b();
    }

    public void b(){
        a();
    }

    //架设这个方法中,处理不了这个异常.方法上抛出异常
    public void test(int a,int b) throws ArithmeticException{//方法上抛出,throws
        if (b == 0){
            throw new ArithmeticException();//主动抛出异常,throw,一般在方法中使用
        }
    }

}
```

